## Uses the Veracode Wrapper docker image: https://hub.docker.com/r/veracode/api-wrapper-java
version: 0.2

env:
  secrets-manager:
    VERACODE_API_KEY_ID: veracode:veracode_api_key_id
    VERACODE_API_KEY_SECRET: veracode:veracode_api_key_secret
phases:
  install:
    commands:
      - echo "System Updating"
      # - apt-get update && apt-get upgrade -y
  post_build:
    commands:
      - echo "Starting Veracode Scan"
      - ls -l
      - cd $CODEBUILD_SRC_DIR_S3_Artifacts
      - ls -l
      - java -jar /opt/veracode/api-wrapper.jar -vid ${VERACODE_API_KEY_ID} -vkey ${VERACODE_API_KEY_SECRET} -action UploadAndScan -createprofile true -appname AWS_${RepoName} -version ${BranchName}-${CommitId} -filepath .
