version: 0.2

phases:
  build:
    commands:
      - echo "Running Veracode IaC/Container/Secrets Scan"
      - cd $CODEBUILD_SRC_DIR_SourceCode
      - curl -fsS https://tools.veracode.com/veracode-cli/install | sh
      - ./veracode scan --type directory --source . --format table
