## Uses Veracode Docker image: https://hub.docker.com/r/veracode/scm-packaging
version: 0.2

env:
  variables:
    VERACODE_CLI_PATH: "/tmp/veracode_cli"
    VERACODE_PACKAGE_OUTPUT_PATH: "veracode_package_artifacts"
phases:
  install:
    commands:
      - echo "System Updating"
      # - apt-get update && apt-get upgrade -y
      - echo "Installing Veracode CLI"
      - mkdir $VERACODE_CLI_PATH
      - cd $VERACODE_CLI_PATH
      - curl -fsS https://tools.veracode.com/veracode-cli/install | sh
      - export PATH="$VERACODE_CLI_PATH:$PATH"
      - veracode version
      - cd $CODEBUILD_SRC_DIR_source2
  build:
    commands:
      - echo "Running Veracode Packaging"
      - ls -l
      - veracode package -s . -a -o $VERACODE_PACKAGE_OUTPUT_PATH
      - ls -l $VERACODE_PACKAGE_OUTPUT_PATH
artifacts:
  base-directory: $CODEBUILD_SRC_DIR_source2
  files:
    - $VERACODE_PACKAGE_OUTPUT_PATH/*
  discard-paths: yes
