version: 0.2

phases:
  install:
    commands:
      - echo "System Updating"
      # - apt-get update && apt-get upgrade -y
      - echo "Installing Veracode CLI"
      - mkdir $VERACODE_CLI_PATH
      - cd $VERACODE_CLI_PATH
      - curl -fsS https://tools.veracode.com/veracode-cli/install | sh
      - export PATH="$VERACODE_CLI_PATH:$PATH"
      - veracode version
      - cd $CODEBUILD_SRC_DIR_Source_Code
  build:
    commands:
      - echo "Running Veracode IaC/Container/Secrets Scan"
      - cd $CODEBUILD_SRC_DIR_SourceCode
      - veracode scan --type directory --source . --format table
